services:
  valkey:
    restart: always
    image: valkey/valkey:9.1.2-alpine
    command: ["--requirepass", "${VALKEY_PASSWORD:?VALKEY_PASSWORD is required}"]
    volumes:
      - "./data:/data"
    ports:
      - 127.0.0.1:30379:6379
